name: tekartik_fs_test
description: Fs test
version: 0.4.3
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.8.0

dependencies:
  fs_shim: ">=2.4.0-1"
  path: ">=1.9.0"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
  dev_test: ">=1.0.0+4"

dev_dependencies:
  test: ">=1.24.0"
  build_runner: ">=2.4.13"
  build_test: '>=0.10.2'
  lints: ">=5.0.0"
  process_run: ">=1.2.1+1"
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_io
      ref: dart3a
  build_web_compilers: ">=4.0.11"

dependency_overrides:
  fs_shim:
    path: ../fs
#  idb_shim:
#    path: ../../idb_shim.dart
