name: tekartik_fs_io
description: Fs for dart io
version: 0.4.1
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.9.0

dependencies:
  path: ">=1.9.0"
  fs_shim: ">=2.3.3+1"
  idb_shim:

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
  dev_build: ">=1.1.2"
  build_runner: ">=2.4.13"
  idb_sqflite:
  sqflite_common_ffi: ">=2.3.4"
  tekartik_fs_test:
    git:
      url: https://github.com/tekartik/fs_shim.dart
      path: fs_test
    version: '>=0.1.0'
  build_test: '>=0.10.2'
  process_run: ">=1.2.1+1"
  tekartik_platform_io:
    git:
      url: https://github.com/tekartik/platform.dart
      path: platform_io
    version: '>=0.2.0'

dependency_overrides:
  fs_shim:
    path: ../fs
  tekartik_fs_test:
    path: ../fs_test

# node_io:
#   git:
#      url: https://github.com/tekartik/node-interop
#      path: node_io
#  node_io:
#    path: /media/ssd/devx/git/github.com/tekartik/node-interop/node_io
#  tekartik_platform:
#    path: /media/ssd/devx/git/github.com/tekartik/platform.dart/platform
#  tekartik_platform_node:
#    path: /media/ssd/devx/git/github.com/tekartik/platform.dart/platform_node
